---
kind: pipeline
type: kubernetes
name: build_image

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: python
  commands:
  - python -m pip install pelican
  - make publish

- name: publish
  image: plugins/docker
  settings:
    repo: toxicglados/blog
    tags: latest
    dry_run: true

