---
kind: pipeline
type: kubernetes
name: build_image

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: python
  commands:
  - python -m pip install pelican['markdown']
  - make publish

- name: publish
  image: plugins/docker
  settings:
    repo: toxicglados/blog
    tags: latest
    username: toxicglados
    password:
      from_secret: docker_password

- name: rollout
  image: toxicglados/drone-rollout:latest
  settings:
    deployment: blog
    namespace: blog
    kubernetes_cert:
      from_secret: KUBERNETES_CERT
    kubernetes_token:
      from_secret: KUBERNETES_TOKEN
